var app = new Vue({
    el: "#app",
    data: {
        books: [
            {
                title: "If minds had toes",
                author: "Lucy Eyre",
                image: "minds-toes.jpg",
                url: "https://www.goodreads.com/book/show/515968.If_Minds_Had_Toes",
                year: 0,
                tags: "fiction, philosophy",
            },
            {
                title: "Metro 2033",
                author: "Dmitry Glukhovsky",
                image: "metro-2033.jpg",
                url: "https://www.goodreads.com/book/show/17274667",
                year: 0,
                tags: "science fiction",
            },
            {
                title: "Without a country",
                author: "Ayşe Kulin, Kenneth Dakan",
                image: "without-a-country.jpg",
                url: "https://www.goodreads.com/book/show/36358350-without-a-country",
                year: 0,
                tags: "historical fiction",
            },
            {
                title: "Rumble fish",
                author: "S.E. Hinton",
                image: "rumble-fish.jpg",
                url: "https://www.goodreads.com/book/show/759960.Rumble_Fish",
                year: 0,
                tags: "fiction, young adult",
            },
            {
                title: "Atlas Shrugged",
                author: "Ayn Rand",
                image: "atlas-shrugged.jpg",
                url: "https://www.goodreads.com/book/show/662.Atlas_Shrugged",
                year: 0,
                tags: "fiction, classics",
            },
            {
                title: "The Book Thief",
                author: "Markus Zusak",
                image: "the-book-thief.jpg",
                url: "https://www.goodreads.com/book/show/562212.Sostiene_Pereira",
                year: 0,
                tags: "historical fiction, war",
            },
            {
                title: "Children of the Sun",
                author: "Alfred W. Crosby",
                image: "children-of-the-sun.jpg",
                url: "https://www.goodreads.com/book/show/1013264.Children_of_the_Sun",
                year: 0,
                tags: "nonfiction, history",
            },
            {
                title: "Mythos",
                author: "Stephen Fry",
                image: "mythos.jpg",
                url: "https://www.goodreads.com/book/show/35074096-mythos",
                year: 0,
                tags: "nonfiction, mythology",
            },
            {
                title: "Treasure Islands",
                author: "Nicholas Shaxson",
                image: "treasure-islands.jpg",
                url: "https://www.goodreads.com/book/show/10197857-treasure-islands",
                year: 0,
                tags: "nonfiction, economics, politics",
            },
            {
                title: "The art of communicating",
                author: "Thich Nhat Hanh",
                image: "art-of-communicating.jpg",
                url: "https://www.goodreads.com/book/show/17331360-the-art-of-communicating",
                year: 0,
                tags: "nonfiction, psychology",
            },
            {
                title: "Mindset: The New Psychology of Success",
                author: "Carol S. Dweck",
                image: "mindset.jpg",
                url: "https://www.goodreads.com/book/show/40745.Mindset",
                year: 0,
                tags: "nonfiction, psychology",
            },
            {
                title: "Thinking, Fast and Slow",
                author: "Daniel Kahneman",
                image: "thinking-fast-and-slow.jpg",
                url: "https://www.goodreads.com/book/show/11468377",
                year: 0,
                tags: "nonfiction, psychology",
            },
            {
                title: "You are not so smart",
                author: "David McRaney",
                image: "you-are-not-so-smart.jpg",
                url: "https://www.goodreads.com/book/show/11709037",
                year: 0,
                tags: "nonfiction, psychology",
            },
            {
                title: "The One Thing",
                author: "Gary Keller, Jay Papasan",
                image: "the-one-thing.jpg",
                url: "https://www.goodreads.com/book/show/16256798-the-one-thing",
                year: 0,
                tags: "nonfiction, psychology",
            },
            {
                title: "The Book of No",
                author: "Susan Newman",
                image: "book-of-no.jpg",
                url: "https://www.goodreads.com/book/show/1168743",
                year: 0,
                tags: "nonfiction, psychology",
            },
            {
                title: "Wij zijn ons brein",
                author: "Dick Swaab",
                image: "wij-zijn-ons-brein.jpg",
                url: "https://www.goodreads.com/book/show/9566672-wij-zijn-ons-brein",
                year: 0,
                tags: "nonfiction, psychology",
            },
            {
                title: "Outliers",
                author: "Malcolm Gladwell",
                image: "outliers.jpg",
                url: "https://www.goodreads.com/book/show/3228917-outliers",
                year: 0,
                tags: "nonfiction, psychology",
            },
            {
                title: "How Fascism Works",
                author: "Jason Stanley",
                image: "how-fascism-works.jpg",
                url: "https://www.goodreads.com/book/show/38255329-how-fascism-works",
                year: 0,
                tags: "politics, nonfiction",
            },
            {
                title: "Nonviolent Communication: A Language of Life",
                author: "Marshall B. Rosenberg",
                image: "nonviolent-communication.jpg",
                url: "https://www.goodreads.com/book/show/71730.Nonviolent_Communication",
                year: 0,
                tags: "psychology, self help",
            },
            {
                title: "Un indovino mi disse",
                author: "Tiziano Terzani",
                image: "",
                url: "https://www.goodreads.com/es/book/show/3786053-un-indovino-mi-disse",
                year: 0,
                tags: "nonfiction, travel",
            },
            {
                title: "American Kingpin",
                author: "Nick Bilton",
                image: "american-kingpin.jpg",
                url: "https://www.goodreads.com/book/show/31920777-american-kingpin",
                year: 0,
                tags: "nonfiction, crime, IT",
            },
            {
                title: "The Big Thirst",
                author: "Charles Fishman",
                image: "the-big-thirst.jpg",
                url: "https://www.goodreads.com/book/show/10503170-the-big-thirst",
                year: 0,
                tags: "nonfiction, science, environment",
            },
            {
                title: "The Macho Paradox",
                author: "Jackson Katz",
                image: "the-macho-paradox.jpg",
                url: "https://www.goodreads.com/book/show/651653.The_Macho_Paradox",
                year: 0,
                tags: "nonfiction, gender",
            },

            {
                title: "The game",
                author: "Neil Strauss",
                image: "the-game.jpg",
                url: "https://www.goodreads.com/book/show/2102001.The_Game",
                year: 2010,
                tags: "nonfiction, biography",
            },
            {
                title: "Io non ho paura",
                author: "Niccolò Ammaniti",
                image: "io-non-ho-paura.jpg",
                url: "https://www.goodreads.com/book/show/13130071-io-non-ho-paura",
                year: 2010,
                tags: "fiction, italy",
            },
            {
                title: "Ranger's Apprentice 01: The Ruins of Gorlan",
                author: "John Flanagan",
                image: "rangers-apprentice-1.jpg",
                url: "https://www.goodreads.com/series/43436-ranger-s-apprentice",
                year: 2009,
                tags: "fiction, fantasy",
            },
            {
                title: "Ranger's Apprentice 02: The Burning Bridge",
                author: "John Flanagan",
                image: "rangers-apprentice-2.jpg",
                url: "https://www.goodreads.com/series/43436-ranger-s-apprentice",
                year: 2009,
                tags: "fiction, fantasy",
            },
            {
                title: "Ranger's Apprentice 03: The Icebound Land",
                author: "John Flanagan",
                image: "rangers-apprentice-3.jpg",
                url: "https://www.goodreads.com/series/43436-ranger-s-apprentice",
                year: 2009,
                tags: "fiction, fantasy",
            },
            {
                title: "Ranger's Apprentice 04: Oakleaf Bearers",
                author: "John Flanagan",
                image: "rangers-apprentice-4.jpg",
                url: "https://www.goodreads.com/book/show/12502050-oakleaf-bearers",
                year: 2009,
                tags: "fiction, fantasy",
            },
            {
                title: "Ranger's Apprentice 05: The Sorcerer in the North",
                author: "John Flanagan",
                image: "rangers-apprentice-5.jpg",
                url: "https://www.goodreads.com/book/show/15783742-the-sorcerer-in-the-north",
                year: 2009,
                tags: "fiction, fantasy",
            },
            {
                title: "Ranger's Apprentice 06: The Siege of Macindaw",
                author: "John Flanagan",
                image: "rangers-apprentice-6.jpg",
                url: "https://www.goodreads.com/book/show/12502132-the-siege-of-macindaw",
                year: 2009,
                tags: "fiction, fantasy",
            },
            {
                title: "Ranger's Apprentice 07: Erak's Ransom",
                author: "John Flanagan",
                image: "rangers-apprentice-7.jpg",
                url: "https://www.goodreads.com/book/show/6851632-erak-s-ransom",
                year: 2009,
                tags: "fiction, fantasy",
            },
            {
                title: "Ranger's Apprentice 08: The Kings of Clonmel",
                author: "John Flanagan",
                image: "rangers-apprentice-8.jpg",
                url: "https://www.goodreads.com/book/show/6851633-the-kings-of-clonmel",
                year: 2009,
                tags: "fiction, fantasy",
            },
            {
                title: "Ranger's Apprentice 09: Halt's Peril",
                author: "John Flanagan",
                image: "rangers-apprentice-9.jpg",
                url: "https://www.goodreads.com/book/show/6348045-halt-s-peril",
                year: 2009,
                tags: "fiction, fantasy",
            },
            {
                title: "Siddharta",
                author: "Herman Hesse",
                image: "siddharta.jpg",
                url: "https://www.goodreads.com/book/show/42639871-siddharta",
                year: 2016,
                tags: "fiction, philosophy",
            },
            {
                title: "The Alchemist",
                author: "Paulo Coelho",
                image: "the-alchemist.jpg",
                url: "https://www.goodreads.com/book/show/18144590-the-alchemist",
                year: 2008,
                tags: "fiction, classics, philosophy",
            },
            {
                title: "Eleven Minutes",
                author: "Paulo Coelho",
                image: "eleven-minutes.jpg",
                url: "https://www.goodreads.com/book/show/1430.Eleven_Minutes",
                year: 2009,
                tags: "fiction, romance",
            },
            {
                title: "Sapiens: A Brief History of Humankind",
                author: "Yuval Noah Harari",
                image: "sapiens.jpg",
                url: "https://www.goodreads.com/book/show/23692271-sapiens",
                year: 2019,
                tags: "nonfiction, history, science",
            },
            {
                title: "Kingkiller Chronicle 1: The Name of the Wind",
                author: "Patrick Rothfuss",
                image: "name-of-the-wind.jpg",
                url: "https://www.goodreads.com/book/show/186074.The_Name_of_the_Wind",
                year: 2010,
                tags: "fiction, fantasy",
            },
            {
                title: "Kingkiller Chronicle 2: The Wise Man's Fear",
                author: "Patrick Rothfuss",
                image: "wise-mans-fear.jpg",
                url: "https://www.goodreads.com/book/show/1215032.The_Wise_Man_s_Fear",
                year: 2010,
                tags: "fiction, fantasy",
            },
            {
                title: "Jonathan Livingston Seagull",
                author: "Richard Bach",
                image: "jonathan-livingston.jpg",
                url: "https://www.goodreads.com/book/show/71728.Jonathan_Livingston_Seagull",
                year: 2017,
                tags: "fiction, classics, philosophy",
            },
            {
                title: "The Hunger Games 1: The Hunger Games",
                author: "Suzanne Collins",
                image: "hunger-games-1.jpg",
                url: "https://www.goodreads.com/book/show/2767052-the-hunger-games",
                year: 2015,
                tags: "fiction, fantasy",
            },
            {
                title: "The Hunger Games 2: Catching Fire",
                author: "Suzanne Collins",
                image: "hunger-games-2.jpg",
                url: "https://www.goodreads.com/book/show/6148028-catching-fire",
                year: 2015,
                tags: "fiction, fantasy",
            },
            {
                title: "The Hunger Games 3: Mockingjay",
                author: "Suzanne Collins",
                image: "hunger-games-3.jpg",
                url: "https://www.goodreads.com/book/show/7260188-mockingjay",
                year: 2015,
                tags: "fiction, fantasy",
            },
            {
                title: "Brave New World",
                author: "Aldous Huxley",
                image: "brave-new-world.jpg",
                url: "https://www.goodreads.com/book/show/5129.Brave_New_World",
                year: 2011,
                tags: "fiction, dystopia",
            },
            {
                title: "1984",
                author: "George Orwell",
                image: "1984.jpg",
                url: "https://www.goodreads.com/book/show/5470.1984",
                year: 2008,
                tags: "fiction, dystopia",
            },
            {
                title: "Animal Farm",
                author: "George Orwell",
                image: "animal-farm.jpg",
                url: "https://www.goodreads.com/book/show/170448.Animal_Farm",
                year: 2019,
                tags: "fiction",
            },
            {
                title: "Down and Out in Paris and London",
                author: "George Orwell",
                image: "down-out-paris-london.jpg",
                url: "https://www.goodreads.com/book/show/393199.Down_and_Out_in_Paris_and_London",
                year: 2017,
                tags: "nonfiction, autobiography",
            },
            {
                title: "Kite Runner",
                author: "Khaled Hosseini",
                image: "kite-runner.jpg",
                url: "https://www.goodreads.com/book/show/20701840-the-kite-runner",
                year: 2019,
                tags: "historical fiction",
            },
            {
                title: "The Motorcycle Diaries",
                author: "Ernesto Che Guevara",
                image: "motorcycle-diaries.jpg",
                url: "https://www.goodreads.com/book/show/832852.The_Motorcycle_Diaries",
                year: 2011,
                tags: "nonfiction, travel, autobiography",
            },
            {
                title: "Letters From Home",
                author: "Kristina McMorris",
                image: "letters-from-home.jpg",
                url: "https://www.goodreads.com/book/show/11238901-letters-from-home",
                year: 2011,
                tags: "historical fiction, romance, war",
            },
            {
                title: "The Notebook",
                author: "Nicholas Sparks",
                image: "the-notebook.jpg",
                url: "https://www.goodreads.com/book/show/33648131-the-notebook",
                year: 2010,
                tags: "fiction, romance",
            },
            {
                title: "Flow: The Psychology of Optimal Experience",
                author: "Mihaly Csikszentmihalyi",
                image: "flow.jpg",
                url: "https://www.goodreads.com/book/show/66354.Flow",
                year: 2018,
                tags: "nonfiction, psychology",
            },
            {
                title: "The Strange Case of Dr. Jekyll and Mr. Hyde",
                author: "Robert Louis Stevenson",
                image: "jekyll-hyde.jpg",
                url: "https://www.goodreads.com/book/show/51496.The_Strange_Case_of_Dr_Jekyll_and_Mr_Hyde",
                year: 2018,
                tags: "fiction, classics",
            },
            {
                title: "Man's Search For Meaning",
                author: "Viktor E. Frankl",
                image: "mans-search-for-meaning.jpg",
                url: "https://www.goodreads.com/book/show/4069.Man_s_Search_for_Meaning",
                year: 2017,
                tags: "nonfiction, autobiography, psychology",
            },
            {
                title: "Istruzioni Per Diventare Fascisti",
                author: "Michela Murgia",
                image: "istruzioni-per-diventare-fascisti.jpg",
                url: "https://www.goodreads.com/book/show/42593767-istruzioni-per-diventare-fascisti",
                year: 2019,
                tags: "nonfiction, politics",
            },
            {
                title: "Het Gouden Ei",
                author: "Tim Krabb\u00e9",
                image: "gouden-ei.jpg",
                url: "https://www.goodreads.com/book/show/2781939-het-gouden-ei",
                year: 2006,
                tags: "fiction",
            },
            {
                title: "Een goede dag voor de ezel",
                author: "Tim Krabb\u00e9",
                image: "een-goede-dag-voor-de-ezel.jpg",
                url: "https://www.goodreads.com/book/show/6090088-een-goede-dag-voor-de-ezel",
                year: 2006,
                tags: "fiction",
            },
            {
                title: "On the Road",
                author: "Jack Kerouac",
                image: "on-the-road.jpg",
                url: "https://www.goodreads.com/book/show/2552.On_the_Road",
                year: 2013,
                tags: "fiction, classics, travel",
            },
            {
                title: "Oeroeg",
                author: "Hella Haase",
                image: "oeroeg.jpg",
                url: "https://www.goodreads.com/book/show/12840125-oeroeg",
                year: 2008,
                tags: "historical fiction",
            },
            {
                title: "Every Time I Find the Meaning of Life, They Change It",
                author: "Daniel Klein",
                image: "find-meaning-of-life.jpg",
                url:
                    "https://www.goodreads.com/book/show/30115065-every-time-i-find-the-meaning-of-life-they-change-it",
                year: 2016,
                tags: "self help, philosophy",
            },
            {
                title: "Appunti per un naufragio",
                author: "Davide Enia",
                image: "appunti-per-un-naufragio.jpg",
                url: "https://www.goodreads.com/book/show/35125188-appunti-per-un-naufragio",
                year: 2019,
                tags: "nonfiction, migrants, refugees",
            },
            {
                title: "Permanent Record",
                author: "Edward Snowden",
                image: "permanent-record.jpg",
                url: "https://www.goodreads.com/book/show/46223297-permanent-record",
                year: 2019,
                tags: "nonfiction, autobiography, surveillance, politics",
            },
            {
                title: "The Long Walk",
                author: "Stephen King",
                image: "the-long-walk.jpg",
                url: "https://www.goodreads.com/book/show/12074735",
                year: 2014,
                tags: "fiction, horror",
            },
            {
                title: "11/22/63",
                author: "Stephen King",
                image: "11-22-63.jpg",
                url: "https://www.goodreads.com/book/show/15739070",
                year: 2012,
                tags: "historical fiction, timetravel",
            },
            {
                title: "Dall'Hindi Kush alle Alpi",
                author: "Fawad e Kaufi",
                image: "hindi-kush-alpi.jpg",
                url: "https://www.goodreads.com/book/show/41433818",
                year: 2020,
                tags: "refugees, migrants, travel, autobiography",
            },
            {
                title: "Red Notice",
                author: "Bill Browder",
                image: "red-notice.jpg",
                url: "https://www.goodreads.com/book/show/41433818",
                year: 2020,
                tags: "autobiography, russia, politics, investing, human rights",
            },
            {
                title: "Il treno dei bambini",
                author: "Viola Ardore",
                image: "il-treno-dei-bambini.jpg",
                url: "https://www.goodreads.com/book/show/52354376",
                year: 2020,
                tags: "historical fiction, post-war",
            },
            {
                title: "Judas",
                author: "Astrid Holleeder",
                image: "judas.jpg",
                url: "https://www.goodreads.com/book/show/32875402",
                year: 2020,
                tags: "nonfiction, crime, autobiography",
            },
            {
                title: "I topi della steppa",
                author: "Sirio Sintoni",
                image: "i-topi-della-steppa.jpg",
                url: "https://www.sintoni.com/index.asp?cat=8&sottocat1=40",
                year: 2020,
                tags: "autobiography, war",
                comments:
                    "Gaat over de ritirata van de fronte russo in 42-43, vanuit de ogen van een soldaat zelf (dit is zijn dagboek)",
            },
            {
                title: "Sostiene Pereira",
                author: "Antonio Tabucchi",
                image: "sostiene-pereira.jpg",
                url: "https://www.goodreads.com/book/show/562212.Sostiene_Pereira",
                year: 2020,
                tags: "fiction",
                comments:
                    "Gaat over een journalist in de tijd vlad voor Salazar in Portugal, en hoe hij en anderen ermee dealen",
            },
            {
                title: "The great Gatsby",
                author: "Scott F. Fitzgerald",
                image: "the-great-gatsby.jpg",
                url: "https://www.goodreads.com/book/show/8701200-the-great-gatsby",
                year: 2020,
                tags: "classics, fiction",
                comments:
                    "Ik vond het boek niet super interessant. Gaat over de extravaganza van de jaren 20 in de VS, waar zich in het boek een love story afspeelt",
            },
            {
                title: "The ungrateful refugee",
                author: "Dina Nayeri",
                image: "the-ungrateful-refugee.jpg",
                url: "https://www.goodreads.com/book/show/43835469-the-ungrateful-refugee",
                year: 2020,
                tags: "nonfiction, autobiography, politics, refugees",
                comments:
                    "Goed boek. Verteld over wat refugees in constant in hun achterhoofd hebben. of ze in deze society passen, de reis die ze hebben gemaakt, enz.",
            },
            {
                title: "The Girl Who Smiled Beads",
                author: "Clemantine Wamariya",
                image: "the-girl-who-smiled-beads.jpg",
                url: "https://www.goodreads.com/book/show/36076501-the-girl-who-smiled-beads",
                year: 2020,
                tags: "nonfiction, autobiography, politics, refugees",
            },
            {
                title: "Long walk to freedom",
                author: "Nelson Mandela",
                image: "long-walk-to-freedom.jpg",
                url: "https://www.goodreads.com/book/show/318431.Long_Walk_to_Freedom",
                year: 2020,
                tags: "biography, nonfiction, history",
            },
            {
                title: "Se questo è un uomo",
                author: "Primo Levi",
                image: "se-questo-e-un-uomo.jpg",
                url: "https://www.goodreads.com/book/show/22597734-se-questo-un-uomo",
                year: 2020,
                tags: "biography, nonfiction, history, ww2",
                comments: "Verteld over hoe het dagelijks leven in een concentratiekamp is",
            },
            {
                title: "How Linux Works",
                author: "Brian Ward",
                image: "how-linux-works.jpg",
                url: "https://www.goodreads.com/book/show/514432",
                year: 2020,
                tags: "IT, linux",
            },
            {
                title: "Factfulness",
                author: "Hans Rosling",
                image: "factfulness.jpg",
                url: "https://www.goodreads.com/book/show/34890015",
                year: 2021,
                tags: "",
                comments: "",
            },
            {
                title: "Koning van Katoren",
                author: "Jan Terlouw",
                image: "koning-van-katoren.jpg",
                url: "https://www.goodreads.com/book/show/1165759",
                year: 2021,
                tags: "fiction",
                comments: "",
            },
        ],
        activeIndex: 2
    },
    methods: {
        getImage: function() {
            let imgUrl = this.books[this.activeIndex].image;
            // return "img/" + imgUrl;

            // template literal
            return `img/${imgUrl}`;
        },
        setActive: function(newIndex) {
            this.activeIndex = newIndex;
        }
    }
})

// ternario
// condizione ? valoreTrue : valoreFalse